### ISSUE TITLE
Docile doesn't load with current sources on 0.5

### ISSUE THREAD

**Issue by protogeezer** [MichaelHatherly/Docile.jl#165] opened 2016-01-06 21:41 UTC
As of the update this morning,

```
julia> using Docile
INFO: Precompiling module Docile...
ERROR: LoadError: LoadError: MethodError: `endswith` has no method matching endswith(::Void, ::ASCIIString)
Closest candidates are:
  endswith(::AbstractString, ::AbstractString)
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 [inlined code] from boot.jl:265
 in anonymous at no file:0
 in eval at ./boot.jl:265
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:222
 in _start at ./client.jl:301
while loading /Users/sjbespa/.julia/v0.5/Docile/src/Utilities.jl, in expression starting on line 118
while loading /Users/sjbespa/.julia/v0.5/Docile/src/Docile.jl, in expression starting on line 44
ERROR: Failed to precompile Docile to /Users/sjbespa/.julia/lib/v0.5/Docile.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:480
 in require at ./loading.jl:339
 in eval at ./boot.jl:265
```
A simple fix appears to be (in utilities.jl)
```julia
# Compat.

if endswith(functionloc(isgeneric)[1], "deprecated.jl")
```
to
```julia
# Compat.

if typeof(functionloc(isgeneric)[1])!=Void &&
	endswith(functionloc(isgeneric)[1], "deprecated.jl")
```

**Comment by MichaelHatherly** [comment] 2016-01-06 22:34
Thanks for the report. Could you provide the output of `versioninfo()`?

I'm on `0.5.0-dev+2021` currently and just tried a fresh install of the package, without hitting the bug you've got. What is the output of `functionloc(isgeneric)` for you? Could you also try commenting out the `__precompile__()` at the start of the package and delete the `.ji` files from `.julia/lib`, then try loading Docile again from a fresh REPL.

**Comment by protogeezer** [comment] 2016-01-06 23:01
Sorry to take so long to reply - I was off doing other things. As you requested, I blew away my “fixed” version to see if I could reproduce the crash:

=========
mbp-et:src sjbespa$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+2021 (2016-01-06 17:45 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit bc1c18e* (0 days old master)
|__/                   |  x86_64-apple-darwin15.3.0

julia> versioninfo()
Julia Version 0.5.0-dev+2021
Commit bc1c18e* (2016-01-06 17:45 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.3.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.rm("Docile")
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.rm("Docile")
INFO: Removing Docile (unregistered)

julia> Pkg.add("Docile")
INFO: Installing Docile v0.5.22
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of Docile
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating Compose master...
INFO: Updating DataArrays master...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using Docile
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.5/Docile.ji for module Docile.
ERROR: LoadError: LoadError: MethodError: `endswith` has no method matching endswith(::Void, ::ASCIIString)
Closest candidates are:
  endswith(::AbstractString, ::AbstractString)
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 [inlined code] from boot.jl:265
 in anonymous at no file:0
 in eval at ./boot.jl:265
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:222
 in _start at ./client.jl:301
while loading /Users/sjbespa/.julia/v0.5/Docile/src/Utilities.jl, in expression starting on line 118
while loading /Users/sjbespa/.julia/v0.5/Docile/src/Docile.jl, in expression starting on line 44
ERROR: Failed to precompile Docile to /Users/sjbespa/.julia/lib/v0.5/Docile.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:480
 in recompile_stale at loading.jl:556
 in _require_from_serialized at loading.jl:164
 in _require_from_serialized at ./loading.jl:193
 in require at ./loading.jl:307
 in eval at ./boot.jl:265

julia> 
==============

**Comment by MichaelHatherly** [comment] 2016-01-06 23:28
> I blew away my “fixed” version to see if I could reproduce the crash

Did you also remove the `__precompile__()` line and empty the `.julia/lib` folder?

What's the output from `functionloc(isgeneric)`?

**Comment by protogeezer** [comment] 2016-01-07 00:39
> On Jan 6, 2016, at 3:28 PM, Michael Hatherly <notifications@github.com> wrote:
> 
> I blew away my “fixed” version to see if I could reproduce the crash
> 
> Did you also remove the __precompile__() line and empty the .julia/lib folder?
> 
> 
No. 
Where is the relevant __precompile__ statement?
and, which folders should I take out of the lib folder?

> What's the output from functionloc(isgeneric)?
> 
> 
julia> functionloc(isgeneric)
(nothing,117)

**Comment by MichaelHatherly** [comment] 2016-01-07 06:35
> Where is the relevant __precompile__ statement?

Since `functionloc(isgeneric)` is returning `nothing` at the REPL this probably has nothing to do with precompiling the package. (For reference though it's [this](https://github.com/MichaelHatherly/Docile.jl/blob/dec23ce619d2d1386188d1625729bec130f7ee4c/src/Docile.jl#L1) and would be the `.julia/lib/Docile.ji` and `.julia/lib/Compat.ji` files that should be removed.)

Does `functionloc` return `nothing` for *every* `Function` you pass to it, or is it specifically `isgeneric`? It's picking up the correct line number though so the problem is probably in the path search. What's the output of the following for you?

```
julia> JULIA_HOME
"/home/mike/usr/julia/master/usr/bin"

julia> Base.DATAROOTDIR
"../share"

julia> methods(isgeneric).defs.func.code.file
symbol("reflection.jl")
```

**Comment by protogeezer** [comment] 2016-01-07 07:11
> On Jan 6, 2016, at 10:35 PM, Michael Hatherly <notifications@github.com> wrote:
> 
> Where is the relevant precompile statement?
> 
> Since functionloc(isgeneric) is returning nothing at the REPL this probably has nothing to do with precompiling the package. (For reference though it's this <https://github.com/MichaelHatherly/Docile.jl/blob/dec23ce619d2d1386188d1625729bec130f7ee4c/src/Docile.jl#L1> and would be the .julia/lib/Docile.ji and .julia/lib/Compat.ji files that should be removed.)
> 
> Does functionloc return nothing for every Function you pass to it, or is it specifically isgeneric? It's picking up the correct line number though so the problem is probably in the path search. What's the output of the following for you?
> 
> ***No - here is the result for a function in one of my modules, and it seems reasonable.Notice I’m using the (semi) out-of-tree build):
> 
julia> include("test_re.jl”)
test_re_balanced (generic function with 1 method)
julia> functionloc(test_re_balanced)
("/Users/sjbespa/vams/test_re.jl",179)
> julia> JULIA_HOME
> "/home/mike/usr/julia/master/usr/bin"
> 
julia> JULIA_HOME
"/Users/sjbespa/work/julia/julia-0.5.0-dev/build/usr/bin”
> julia> Base.DATAROOTDIR
> "../share"
> 
julia> Base.DATAROOTDIR
"../share"
> julia> methods(isgeneric).defs.func.code.file
> symbol("reflection.jl”)

julia> methods(isgeneric).defs.func.code.file
symbol("reflection.jl")

**Comment by MichaelHatherly** [comment] 2016-01-07 08:29
> (semi) out-of-tree build

That would probably be the culprit then. `Base.find_source_file`, which is called by `functionloc`, seems to be getting confused that the `"reflection.jl"` file isn't in the right place.

Is the path created by `find_source_file`, i.e.

```
joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "base", "reflection.jl")
```

pointing to the right place?

**Comment by MichaelHatherly** [comment] 2016-01-07 08:46
Just finished an out-of-tree build with `make O=build`. `functionloc(isgeneric)` does return the correct path. What were the steps you took in building your out-of-tree?

**Comment by protogeezer** [comment] 2016-01-07 19:08
Maybe you didn't cd into the out-of-tree build directory?
`
Last login: Thu Jan  7 09:48:55 on ttys000
mbp-et:~ sjbespa$ cd work/julia
mbp-et:julia sjbespa$ git clone git://github.com/JuliaLang/julia.git julia-0.5
Cloning into 'julia-0.5'...
remote: Counting objects: 164196, done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 164196 (delta 17), reused 0 (delta 0), pack-reused 164128
Receiving objects: 100% (164196/164196), 92.56 MiB | 264.00 KiB/s, done.
Resolving deltas: 100% (125067/125067), done.
Checking connectivity... done.
mbp-et:julia sjbespa$ cd julia-0.5
mbp-et:julia-0.5 sjbespa$ mkdir build
mbp-et:julia-0.5 sjbespa$ make O=build configure
Building into /Users/sjbespa/work/julia/julia-0.5/build
mbp-et:julia-0.5 sjbespa$ cd build
mbp-et:build sjbespa$ make -j4
Creating usr/etc/julia/juliarc.jl
Copying in usr/share/doc/julia/examples
Copying in usr/share/man/man1/julia.1

blah, blah, blah

/Users/sjbespa/work/julia/julia-0.5/base/precompile.jl
    LINK build/usr/lib/julia/sys.dylib
mbp-et:build sjbespa$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+2028 (2016-01-07 15:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit bef2b08* (0 days old master)
|__/                   |  x86_64-apple-darwin15.3.0

julia> functionloc(isgeneric)
(nothing,117)

julia> pwd()
"/Users/sjbespa/work/julia/julia-0.5/build"

julia>
`
I've been experimenting with build options that would allow me to move parts of julia into Qt - so having parallel, but separate build directories, is enabling.

Stephen

**Comment by protogeezer** [comment] 2016-01-07 19:39
The path evaluates to:

```
julia> joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "base", "reflection.jl")
"/Users/sjbespa/work/julia/julia-0.5/build/usr/bin/../share/julia/base/reflection.jl”
```

the file is actually in:
```
Last login: Thu Jan  7 11:19:30 on ttys001
mbp-et:~ sjbespa$ cd /Users/sjbespa/work/julia/julia-0.5/base 
mbp-et:base sjbespa$ ls ref*
reflection.jl	refpointer.jl
```

Stephen

**Comment by MichaelHatherly** [comment] 2016-01-07 20:05
OK, looks as though this should just be fixed in the base. Best if you either open an issue in the main julia repo, or a PR to fix it.

**Comment by protogeezer** [comment] 2016-01-07 21:39
Ok thanks. I’ll submit the issue since I’m not entirely clear on where to insert a fix down in the base code, and I don’t have time to figure it out.

If I might ask a somewhat off the topic question, why do some of my messages format correctly wrt the code blocks, and some, like my previous message just end up with reverse tick marks and unformatted code?

Stephen

**Comment by MichaelHatherly** [comment] 2016-01-07 22:04
I'll also look into sorting out something on the Docile side in the meantime, probably tomorrow morning.

> why do some of my messages format correctly wrt the code blocks,

The very first message I reformatted so I could read the error message a bit easier. The others are just how github handles email replies I believe.

**Closed** 2016-01-08 08:09 UTC
Labels: upstream

**Comment by MichaelHatherly** [comment] 2016-01-08 08:11
Closed with fix on the Docile side, underlying issue with out of tree builds still exists though.
